---
title: "Portfolio2"
author: "Line Kruse"
date: "3/18/2020"
output: html_document
---

```{r setup, include=FALSE}

set.seed(1982)
library(pacman)
p_load(R2jags, extraDistr, ggplot2)

setwd("~/Documents/Advanced Cognitive Modeling /Exercise 2 - Models for bandit arms task/KernelModel")

```

#Set up task environment 

```{r}
#Generate task environment 
#Two bandits for the agents to choose from 
ntrials <- 100 
Aprob <- 0.3
Arew <- 2 

Bprob <- 0.8 
Brew <- 1

#Payoff matrix that draws from separate distributions, defined above 
payoff <- cbind(rbinom(ntrials, 1, Aprob)*Arew, rbinom(ntrials,1,Bprob)*Brew)

#Which bandit gives larger benefit in the long run 
colSums(payoff) #Bandit B 

```

#Run parameter recovery 
```{r}
################## RW model (Q-learning) ##################
recRW <- paramRecRW(100, "RW_learning_model_jags.txt")

source("quick_n_clean_plots.R")
p1 <- plot_scatter(recRW$trueAlpha, recRW$inferredAlpha)
p1a <- plot_actual_predicted(recRW$trueAlpha, recRW$inferredAlpha)

p2 <- plot_scatter(recRW$trueBeta, recRW$inferredBeta)
p2a <- plot_actual_predicted(recRW$trueBeta, recRW$inferredBeta)

p1b <- plot_dens(recRW$trueBeta)
p1c <- plot_dens(recRW$inferredBeta)

################## Kernel model  ##################
recKernel <- paramRecKernel(100, "kernal.txt")

source("quick_n_clean_plots.R")
p1 <- plot_scatter(recKernel$trueAlpha, recKernel$inferredAlpha)
p3a <- plot_actual_predicted(recKernel$trueAlpha, recKernel$inferredAlpha)

p2 <- plot_scatter(recKernel$trueBeta, recKernel$inferredBeta)
p4a <- plot_actual_predicted(recKernel$trueBeta, recKernel$inferredBeta)

p1b <- plot_dens(recKernel$trueBeta)
p1c <- plot_dens(recKernel$inferredBeta)

```

#Run model recovery 

```{r}

z <- modelRecovery(100)


######## CREATE CONFUSION MATRIX OF PROPORTION THE CORRECT MODEL WAS CHOSEN
dic_RW_model <- data.frame(RW_data = z$DIC.RW_RW, kernel_data = z$DIC.Kernel_RW)
dic_Kernel_model <- data.frame(RW_data = z$DIC.RW_Kernel, kernel_data = z$DIC.Kernel_Kernel)

min_dic_RW_model <- apply(dic_RW_model, 1, which.min)
min_dic_kernel_model <- apply(dic_Kernel_model, 1, which.min)

n_sims <- 100
dic_df <- data.frame(predictions = c(min_dic_RW_model, min_dic_kernel_model), true = c(rep('RW', n_sims), rep('Kernal', n_sims))) %>% 
  mutate(predictions = as.character(predictions)) %>%
  mutate(predictions = recode(predictions, '1' = 'RW', '2' = 'Kernal'))# %>% 

devtools::install_github("ludvigolsen/cvms", ref="hparams_tuning")
library(cvms)

conf_mat <-  confusion_matrix(dic_df$true, dic_df$predictions)
cf_mat <- conf_mat$`Confusion Matrix`[[1]]

CM <- plot_confusion_matrix(cf_mat, add_row_percentages = F, add_col_percentages = T, add_normalized = T, counts_on_top = F)


```

# 1) Source functions for simulating data - Q-learning model and Kernel Model 
```{r}
################# Simulation RW model (Q-learning) #################
source("RW_learning_function.R")
source("KernelModel_function.R")

```

# 2) Functions for making inferences from the model (infer paramaters from fitting the model to the data)

```{r cars}

################# Inference Function - Fixed model #################
#G = Gfixed or Glearn
#Model = "jagsModel1.txt", "jagsModel2.txt" 

inferenceRW <- function(x, r, model){

  ntrials <- 100
  data <- list("x", "r", "ntrials")
  params <- c("a", "beta")
  
  samples <- jags(data, inits=NULL, params, 
                  model.file = model, 
                  n.chains = 3, 
                  n.iter = 5000, 
                  n.burnin = 1000,
                  n.thin = 1) 
  
  return(samples)
}


################# Inference Function - Learning model #################
inferenceKernel <- function(x,r, model){

  ntrials <- 100
  data <- list("x", "r", "ntrials")
  params <- c("a", "beta")
  
  samples <- jags(data, inits=NULL, params, 
                  model.file = model, 
                  n.chains = 3, 
                  n.iter = 5000, 
                  n.burnin = 1000,
                  n.thin = 1) 
  
  return(samples)
}



```

# 3) Iterative parameter recovery functions - RW model and Kernel model 

```{r pressure, echo=FALSE}

############### Parameter Recovery - Fixed Model  #################
#Model = "jagsModel1.txt" or "jagsModel2.txt"
paramRecRW <- function(iterations, model){
  
  trueAlpha <- array(0, c(iterations))
  inferredAlpha <- array(0, c(iterations))
  
  trueBeta <- array(0, c(iterations))
  inferredBeta <- array(0, c(iterations))
  
  for (i in 1:iterations){
    a <- runif(1,0,1) 
    beta <- rgamma(1,1,1)
    
    #Run function and extract respones 
    RW_sims <- RW(payoff, ntrials, a, beta)
    x <- RW_sims$x
    r <- RW_sims$r
    
    #Run parameter inference 
    samples <- inferenceRW(x,r, model)
    
    #Record values 
    trueAlpha[i] <- a 
    trueBeta[i] <- beta
    
    post_a <- samples$BUGSoutput$sims.list$a
    post_beta <- samples$BUGSoutput$sims.list$beta
  
    inferredAlpha[i] <- density(post_a)$x[which(density(post_a)$y==max(density(post_a)$y))]
    inferredBeta[i] <- density(post_beta)$x[which(density(post_beta)$y==max(density(post_beta)$y))]
  }
  return(list(trueAlpha=trueAlpha, inferredAlpha=inferredAlpha, trueBeta=trueBeta, inferredBeta = inferredBeta))
}



############### Parameter Recovery - Learning Model  #################
#Model = "jagsModel1.txt" or "jagsModel2.txt"
paramRecKernel <- function(iterations, model){
  trueAlpha <- array(0, c(iterations))
  inferredAlpha <- array(0, c(iterations))
  
  trueBeta <- array(0, c(iterations))
  inferredBeta <- array(0, c(iterations))
  
  for (i in 1:iterations){
   a <-runif(1,0,1)
   beta <- rgamma(1,1,1)
    
    #Run function and extract respones 
    kernel_sims <- kernel(payoff, ntrials, a, beta)
    x <- kernel_sims$x
    r <- kernel_sims$r
    
    #Run parameter inference 
    samples <- inferenceKernel(x,r, model)
    
    #Record values 
    trueAlpha[i] <- a 
    trueBeta[i] <- beta
    
    post_a <- samples$BUGSoutput$sims.list$a
    post_beta <- samples$BUGSoutput$sims.list$beta
  
    inferredAlpha[i] <- density(post_a)$x[which(density(post_a)$y==max(density(post_a)$y))]
    inferredBeta[i] <- density(post_beta)$x[which(density(post_beta)$y==max(density(post_beta)$y))]
  }
  
  return(list(trueAlpha=trueAlpha, inferredAlpha=inferredAlpha, trueBeta=trueBeta, inferredBeta = inferredBeta))
  
}


```

# 4) Model recovery functions - RW model and Kernel model 

```{r}
modelRecovery <- function(rounds){
  
  DIC.RW_RW <- array(0,c(rounds))
  DIC.RW_Kernel <- array(0,c(rounds))

  DIC.Kernel_Kernel <- array(0,c(rounds))
  DIC.Kernel_RW <- array(0,c(rounds))
  
  for (i in 1:rounds){
    a <-runif(1,0,1)
    beta <- rgamma(1,1,1)
    
    RW_sims <- RW(payoff, ntrials, a, beta)
    RW_x <- RW_sims$x
    RW_r <- RW_sims$r
    
    kernel_sims <- kernel(payoff, ntrials, a, beta)
    kernel_x <- kernel_sims$x
    kernel_r <- kernel_sims$r
    
    RW_RW_Samples <- inferenceRW(RW_x, RW_r, "RW_learning_model_jags.txt") #RW data and RW model 
    RW_Kernel_Samples <- inferenceKernel(RW_x, RW_r, "kernal.txt") #RW data and kernel model 
    
    Kernel_RW_Samples <- inferenceRW(kernel_x, kernel_r, "RW_learning_model_jags.txt") #kernel data and RW model 
    Kernel_Kernel_Samples <- inferenceKernel(kernel_x, kernel_r, "kernal.txt") #kernel data and kernel model 
    
    DIC.RW_RW[i] <- RW_RW_Samples$BUGSoutput$DIC #RW data and RW model 
    DIC.RW_Kernel[i] <- RW_Kernel_Samples$BUGSoutput$DIC #RW data and kernel model 
    DIC.Kernel_RW[i] <- Kernel_RW_Samples$BUGSoutput$DIC #kernel data and RW model 
    DIC.Kernel_Kernel[i] <- Kernel_Kernel_Samples$BUGSoutput$DIC #kernel data and kernel model 

  }
  return(list(DIC.RW_RW=DIC.RW_RW, DIC.RW_Kernel = DIC.RW_Kernel, DIC.Kernel_RW=DIC.Kernel_RW, DIC.Kernel_Kernel = DIC.Kernel_Kernel))
  
}

```
