---
title: "CC_paramRec"
author: "Line Kruse"
date: "4/20/2020"
output: html_document
---

```{r setup, include=FALSE}
set.seed(1982)
library(pacman)
p_load(R2jags, polspline, extraDistr, ggplot2)
```

#Run parameter recovery - CC model 

```{r}

recCC <- paramRecCC(100)
save(recCC, file="recCC_2.Rdata")
load("recCC_2.Rdata")

source("quick_n_clean_plots.R")
p_omega1_s1 <- plot_actual_predicted(recCC$true$omega1[1,],recCC$MAP$omega1[1,], title="A) Omega1: S1")
p_omega1_s2 <- plot_actual_predicted(recCC$true$omega1[2,],recCC$MAP$omega1[2,], title="B) Omega1: S2")
p_omega1_s3 <- plot_actual_predicted(recCC$true$omega1[3,],recCC$MAP$omega1[3,], title="C) Omega1: S3")

p_lambda_s1 <- plot_actual_predicted(recCC$true$lambda[1,],recCC$MAP$lambda[1,], title="A) Lambda: S1")
p_lambda_s2 <- plot_actual_predicted(recCC$true$lambda[2,],recCC$MAP$lambda[2,], title="B) Lambda: S2")
p_lambda_s3 <- plot_actual_predicted(recCC$true$lambda[3,],recCC$MAP$lambda[3,], title="C) Lambda: S3")

p_gamma_s1 <- plot_actual_predicted(recCC$true$gamma[1,],recCC$MAP$gamma[1,], title="A) Gamma: S1")
p_gamma_s2 <- plot_actual_predicted(recCC$true$gamma[2,],recCC$MAP$gamma[2,], title="B) Gamma: S2")
p_gamma_s3 <- plot_actual_predicted(recCC$true$gamma[3,],recCC$MAP$gamma[3,], title="C) Gamma: S3")

p_pbeta_s1 <- plot_actual_predicted(recCC$true$pbeta[1,],recCC$MAP$pbeta[1,], title="A) pBeta: S1")
p_pbeta_s2 <- plot_actual_predicted(recCC$true$pbeta[2,],recCC$MAP$pbeta[2,], title="B) pBeta: S2")
p_pbeta_s3 <- plot_actual_predicted(recCC$true$pbeta[3,],recCC$MAP$pbeta[3,], title="C) pBeta: S3") 


p_omega_s1_t1 <- plot_actual_predicted(recCC$true$omega[1,1,],recCC$MAP$omega[1,1,], title="C) Gamma: S3 t1") 

```

#Parameter recovery function - CC model 

```{r}
paramRecCC <- function(niterations){
  
  ntrials <- 15
  nagents <- 3
  vals <- seq(1,20,1) #Possible values to contribute, from 0 to 20 tokens 
  
  #Empty data frames to fill with true parameters 
  true <- c()
  true$omega1 <- array(0, c(nagents, niterations)) #Weighting for beliefs vs preferences on first trial 
  true$lambda <- array(0, c(nagents, niterations)) #Decay rate for weigthing for beliefs - speed that peferences dominate over time 
  true$gamma <- array(0, c(nagents, niterations)) #Learning rate for beliefs in others contribution 
  true$pbeta <- array(0, c(nagents, niterations)) #Slope for model relating others' contributions and own preferences 
  true$omega <- array(0, c(nagents,ntrials,niterations))
  
  #Empty data frames to fill with parameter estimates from jags model 
  MAP <- c()
  MAP$omega1 <- array(0, c(nagents, niterations))
  MAP$lambda <- array(0, c(nagents, niterations))
  MAP$gamma <- array(0, c(nagents, niterations))
  MAP$pbeta <- array(0, c(nagents, niterations))
  MAP$omega <- array(0,c(nagents, ntrials, niterations))
  
  for (i in 1:niterations){
    
    for(n in 1:nagents){
      #Random draw of true parameter values 
      true$omega1[n,i] <- runif(1,0,1)
      true$lambda[n,i] <- runif(1,0,1)
      true$gamma[n,i] <- runif(1,0,1)
      true$pbeta[n,i] <- runif(1,0,1)
    }
    
    for (n in 1:nagents){
      true$omega[n,1,i] <- true$omega1[n,i]
      
      for(t in 2:ntrials){
        true$omega[n,t,i] <- true$omega[n,t-1,i]*(1-true$lambda[n,i])
      }
    }
    
    #Load and run simulation function 
    source("CC_sim_function.R")
    
    parameters <- c()
    parameters$Gb1 <- runif(3,0,20)
    parameters$omega1 <- true$omega1[,i]
    parameters$lambda <- true$lambda[,i]
    parameters$gamma <- true$gamma[,i]
    parameters$pbeta <- true$pbeta[,i]
    parameters$p0 <- rep(0,nagents)
    
    CC_sims <- CC_function(nagents, ntrials, vals, parameters)
  
    c <- CC_sims$c
    Ga <- CC_sims$Ga
    
    data <- list("nagents", "ntrials", "vals", "c", "Ga")
    params <- c("omega1", "lambda", "gamma", "p0", "pbeta", "c", "omega")
    samples <- jags.parallel(data, inits=NULL, params,
                             model.file ="CC_model_jags.txt",
                             n.chains=3, n.iter=5000, n.burnin=1000, n.thin=1)
    
    post_omega1 <- samples$BUGSoutput$sims.list$omega1
    post_lambda <- samples$BUGSoutput$sims.list$lambda
    post_gamma <- samples$BUGSoutput$sims.list$gamma
    #post_p0 <- samples$BUGSoutput$sims.list$p0
    post_pbeta <- samples$BUGSoutput$sims.list$pbeta
    #post_c <- samples$BUGSoutput$sims.list$c
    post_omega <- samples$BUGSoutput$sims.list$omega 
    
    #MAP$c <- density(post_c)$x[which(density(post_c)$y==max(density(post_c)$y))]
    
    for (n in 1:nagents){
      MAP$omega1[n,i] <- density(post_omega1[,n])$x[which(density(post_omega1[,n])$y==max(density(post_omega1[,n])$y))]
      MAP$lambda[n,i] <- density(post_lambda[,n])$x[which(density(post_lambda[,n])$y==max(density(post_lambda[,n])$y))]
      MAP$gamma[n,i] <- density(post_gamma[,n])$x[which(density(post_gamma[,n])$y==max(density(post_gamma[,n])$y))]
      #MAP$p0[n,i] <- density(post_p0[,n])$x[which(density(post_p0[,n])$y==max(density(post_p0[,n])$y))]
      MAP$pbeta[n,i] <- density(post_pbeta[,n])$x[which(density(post_pbeta[,n])$y==max(density(post_pbeta[,n])$y))]
      for(t in 2:ntrials){
      MAP$omega[n,t,i] <- density(post_omega[,n,t])$x[which(density(post_omega[,n,t])$y==max(density(post_omega[,n,t])$y))]}
      
    }
  }  
  return(list(true=true, MAP=MAP))
}

#post_omega <- [sample, agent, trial]
omega_list <- array(0, c(nagents,ntrials))
for (n in 1:nagents){
  true_omega[n,1] <- omega1
  
  for(t in 2:ntrials){
    true_omega[n,t] <- omega[n,t-1]*(1-lambda[n])
  }
}



```


