---
title: "Latent Mixture Model - Public Goods Game"
author: "Line Kruse"
date: "4/27/2020"
output: html_document
---

```{r setup, include=FALSE}
set.seed(1982)
library(pacman)
p_load(R2jags, polspline, readxl)
```

#Prepare data for latent mixture model 
#The model uses both the EWA and CC model (coded separately in exercise 5)

```{r}
rawDat <- read.csv("~/Documents/Advanced Cognitive Modeling /Exercise 6 - Latent mixture models of public goods game /data.csv", header=TRUE)

max_nsubs <- 100
pi <- 3
ntokens <- 20
vals <- seq(1,20,1) #possible values to contribute - from 0 to 20 tokens

rawPercContrib <- rawDat$Percent.of.endowment.contributed.to.group.account
roundTokenContrib <- round(rawPercContrib/5)

subNo <- rawDat$Unique.subject.identifier
groupNo <- rawDat$Unique.group.identifier
trialNo <- rawDat$Round

uniqueSubs <- unique(subNo)
uniqueGroups <- unique(groupNo)

n_uniqueSubs <- length(uniqueSubs)
ngroups <- length(uniqueGroups)

# check whether each subject completed all 7 rounds - all do
ntrials_bySub <- array(0,c(n_uniqueSubs))
for (i in 1:length(uniqueSubs)) {
  ntrials_bySub[i] <- max(trialNo[subNo==uniqueSubs[i]])
}
min(ntrials_bySub)

ntrials <- 7

# subject x round x group token contributions
subTrialContrib <- array(0,c(length(uniqueSubs),ntrials))
for (s in 1:length(uniqueSubs)) {
  subTrialContrib[s,] <- roundTokenContrib[subNo==uniqueSubs[s]] 
}

# make an array that tells you which group each subject is in
subGroupNo <- array(0,c(length(uniqueSubs)))
for (s in 1:length(uniqueSubs)) {
  subGroupNo[s] <- mean(groupNo[subNo==uniqueSubs[s]])
}

# make an array that tells you the size if the group each subject is in
subGroupNo <- array(0,c(length(uniqueSubs)))
for (s in 1:length(uniqueSubs)) {
  subGroupNo[s] <- mean(groupNo[subNo==uniqueSubs[s]])
}


# make matrices to input into JAGS - a subject * trial * group matrix c, and a groupSize vector for the 51 groups
c <- array(0,c(max_nsubs,ntrials,length(uniqueGroups)))
groupSize <- array(0,c(ngroups))
Ga <- array(0,c(ntrials,ngroups))
Gc <- array(0,c(max_nsubs,ntrials,ngroups))

for (g in 1:ngroups) {

  matToAssign <- subTrialContrib[subGroupNo==uniqueGroups[g],]
  groupSize[g] <- length(matToAssign[,1])
  c[1:groupSize[g],,g] <- subTrialContrib[subGroupNo==uniqueGroups[g],]
  Ga[,g] <- colMeans(matToAssign)
  
  for (s in 1:groupSize[g]) {
    Gc[s,,g] <- colSums(matToAssign[-s,])
  }
}

# re-representation of contribution not as data but as model input, for attraction equation
c_choice_index <- c
```

#Fit hierarchical latent mixture model 

```{r}
data <- list("groupSize", "ngroups", "ntrials", "ntokens", "pi", "vals","c","Gc","c_choice_index","Ga") #data inputted into jags
params <- c("Z","mu","beta0","betaG", "psy") #parameters we'll track in jags

samples <- jags.parallel(data, inits=NULL, params,
                model.file ="hierLMM_publicGoods.txt",
                n.chains=3, n.iter=5000, n.burnin=1000, n.thin=1)
samples
save(samples, file="hierLMM_samples.Rdata")
load("hierLMM_samples.Rdata")
```

#Extract posterior distributions and MAP 
#Do some people tend to use one strategy (EWA model or CC model) over the other? 
#Does the proportion of strategies used chance depending on group size? 

```{r}

#Extract posterior distributions and plot them 
betaG_post <- samples$BUGSoutput$sims.list$betaG
beta0_post <- samples$BUGSoutput$sims.list$beta0
Z_post <- samples$BUGSoutput$sims.list$Z
psy_post <- samples$BUGSoutput$sims.list$psy

png("LMM_posteriors.png") 
par(mfrow=c(2,2))
plot(density(beta0_post), main="Intercept(beta0)")
plot(density(betaG_post), main="Slope (betaG)")
dev.off()



#Calculate Bayes Factor on betaG
prior <- dnorm(0,1)
fit.posterior <- logspline(samples$BUGSoutput$sims.list$betaG)
posterior <- dlogspline(0, fit.posterior) # this gives the pdf at point delta = 0

#BF01 - increase in belief that there IS an effect 
prior/posterior #10218.89

#BF10 - increase in belief that there is NO effect 
posterior/prior #9.7858e-05


qlogspline(0.025,fit.posterior) #2.5% CI 
#0.2325
qlogspline(0.975,fit.posterior) #97.5% CI
#1.175499

# intercept
beta0_MAP <- density(samples$BUGSoutput$sims.list$beta0)$x[which(density(samples$BUGSoutput$sims.list$beta0)$y==max(density(samples$BUGSoutput$sims.list$beta0)$y))] 
#slope
betaG_MAP <-density(samples$BUGSoutput$sims.list$betaG)$x[which(density(samples$BUGSoutput$sims.list$betaG)$y==max(density(samples$BUGSoutput$sims.list$betaG)$y))] #MAP

#pobability of conditional co-operation in each group size
p0_CC <- pnorm(beta0_MAP) #0.0319
p10_CC <- p0_CC + (p100_CC - p0_CC)/10 #0.0378
p40_CC <- p10_CC*4 #0.1512
p100_CC <- pnorm(beta0_MAP+betaG_MAP) #0.0909

#Psy is probability of CC model 
psyMAP <- array(0,c(max_nsubs,ngroups))

for (g in 1:ngroups) {
  for (s in 1:groupSize[g]) {
    X <- samples$BUGSoutput$sims.list$psy[,s,g]
    psyMAP[s,g] <-density(X)$x[which(density(X)$y==max(density(X)$y))]
  }
}


```


