---
title: "VSE model"
author: "Line Kruse"
date: "3/21/2020"
output: html_document
---

```{r setup, include=FALSE}
library(pacman)
set.seed(1982)
p_load(extraDistr, R2jags)
setwd("~/Documents/Advanced Cognitive Modeling /Exercise3 - Iowa Gambling Task")
```

#Set up task environment 

```{r}
#Bad frequent deck 
A_R <- rep(100,10) #reward for deck A (10 trials)
A_L <- c(rep(-250,5),rep(0,5)) #Loss for deck A - 5/10 you get big loss, 5/10 you dont loose anything.

#Bad infrequent deck
B_R <- rep(100,10)
B_L <- c(rep(-1200,1),rep(0,9)) #1/10 you get major loss, 9/10 you dont loose anything. 

#Good frequent deck 
C_R <- rep(50,10) 
C_L <- c(rep(-50,5),rep(0,5)) 

#Good infrequent deck
D_R <- rep(50,10)
D_L <- c(rep(-250,1),rep(0,9)) 

#Shuffle decks and store them in arrays 
#We only shuffle the Losses because the rewards are always the same in each decl 

#Outcome of A 
A <- c()
for(i in 1:10){
  A <- (append(A,A_R+sample(A_L)))
}

#Outcome of B
B <- c()
for(i in 1:10){
  B <- (append(B,B_R+sample(B_L)))
}

#Outcome of C
C <- c()
for(i in 1:10){
  C <- (append(C,C_R+sample(C_L)))
}

#Outcome of D
D <- c()
for(i in 1:10){
  D <- (append(D,D_R+sample(D_L)))
}

#Extract rewards from reward trials
RA <- A
RA[A < 0] = 0
RB <- B
RB[B < 0] = 0
RC <- C
RC[C < 0] = 0
RD <- D
RD[D < 0] = 0

#Extract losses from reward trials
LA <- A
LA[A > 0] = 0
LB <- B
LB[B > 0] = 0
LC <- C
LC[C > 0] = 0
LD <- D
LD[D > 0] = 0

R <- cbind(RA,RB,RC,RD)
L <- cbind(LA,LB,LC,LD)
L <- abs(L)
R <- R

R <- R/100
L <- L/100

```

#Set parameters and run forward simulation 

```{r}
theta <- 0.3 #risk preference for the utility function (bounded between 0 and 1)
delta <- 0.2 #decay rate for value learning function (bounded between 0 and 1)
a <- 0.3 #learning rate for sequential exploration function (bounded betwee 0 and 1)
phi <- 0.4 #maximum/asymptote for the sequential exploration function (unbounded, can be positive and negative)
C <- 2 #softmax inverse heat parameter (bounded between 0 and 5)

ntrials <- 100 

source("VSE_Model_function.R")
VSE_sim <- VSE_model(R, L, ntrials, theta, delta, a, phi, C)
VSE_sim$Exploit

#Plot results 
par(mfrow=c(2,2))
plot(ORL_sim$Exploit[,1])
plot(ORL_sim$Exploit[,2])
plot(ORL_sim$Exploit[,3])
plot(ORL_sim$Exploit[,4])

```

#Fit VSE jags model - inference 

```{r}

x <- VSE_sim$x
r <- VSE_sim$r
l <- VSE_sim$l

data <- list("x", "r", "l", "ntrials")
params <- c("theta", "delta", "a", "phi", "C")

samples <- jags.parallel(data, inits = NULL, params, 
                         model.file = "VSE_Model_jags.txt", 
                         n.chains =3, n.iter =5000, n.burnin = 1000, n.thin = 1)


post_theta <- samples$BUGSoutput$sims.list$theta
post_delta <- samples$BUGSoutput$sims.list$delta
post_a <- samples$BUGSoutput$sims.list$a
post_phi <- samples$BUGSoutput$sims.list$phi
post_C <- samples$BUGSoutput$sims.list$C

plot_dens(post_theta)
plot_dens(post_delta)
plot_dens(post_a)
plot_dens(post_phi)
plot_dens(post_C)

```

#Parameter recovery 

```{r}
p_load(ggplot2)

source("VSE_Model_function.R")
recVSE <- paramRecVSE(100, "VSE_Model_jags.txt")

source("quick_n_clean_plots.R")
p_theta <- plot_actual_predicted(recVSE$trueTheta,recVSE$inferredTheta)

p_delta <- plot_actual_predicted(recVSE$trueDelta,recVSE$inferredDelta)

p_A <- plot_actual_predicted(recVSE$trueA,recVSE$inferredA)

p_phi <- plot_actual_predicted(recVSE$truePhi,recVSE$inferredPhi)

p_C <- plot_actual_predicted(recVSE$trueC,recVSE$inferredC)

paramRecVSE <- function(iterations, model){
  trueTheta <- array(0, c(iterations))
  inferredTheta <- array(0, c(iterations))
  
  trueDelta <- array(0, c(iterations))
  inferredDelta <- array(0, c(iterations))
  
  trueA <- array(0, c(iterations))
  inferredA <- array(0, c(iterations))
  
  truePhi <- array(0, c(iterations))
  inferredPhi <- array(0, c(iterations))
  
  trueC <- array(0, c(iterations))
  inferredC <- array(0, c(iterations))
  
  for (i in 1:iterations){
    theta <-runif(1,0,1)
    delta <-runif(1,0,1)
    a <- runif(1,0,1)
    phi <- runif(1,-2,2)
    C <- runif(1,0,5)
    
    #Run function and extract respones 
    VSE_sim <- VSE_model(R, L, ntrials, theta, delta, a, phi, C)
    x <- VSE_sim$x
    r <- VSE_sim$r
    l <- VSE_sim$l
    
    #Run parameter inference 
    data <- list("x", "r", "l", "ntrials")
    params <- c("theta", "delta", "a", "phi", "C")

    samples <- jags.parallel(data, inits = NULL, params, 
                         model.file = model, 
                         n.chains =3, n.iter =5000, n.burnin = 1000, n.thin = 1)
    
    #Record values 
    trueTheta[i] <- theta
    trueDelta[i] <- delta
    trueA[i] <- a
    truePhi[i] <- phi
    trueC[i] <- C
    
    post_theta <- samples$BUGSoutput$sims.list$theta
    post_delta <- samples$BUGSoutput$sims.list$delta
    post_a <- samples$BUGSoutput$sims.list$a
    post_phi <- samples$BUGSoutput$sims.list$phi
    post_C <- samples$BUGSoutput$sims.list$C
    
    inferredTheta[i] <- density(post_theta)$x[which(density(post_theta)$y==max(density(post_theta)$y))]
    inferredDelta[i] <- density(post_delta)$x[which(density(post_delta)$y==max(density(post_delta)$y))]
    inferredA[i] <- density(post_a)$x[which(density(post_a)$y==max(density(post_a)$y))]
    inferredPhi[i] <- density(post_phi)$x[which(density(post_phi)$y==max(density(post_phi)$y))]
    inferredC[i] <- density(post_C)$x[which(density(post_C)$y==max(density(post_C)$y))]
  }
  
  return(list(trueTheta=trueTheta, inferredTheta=inferredTheta, trueDelta=trueDelta, inferredDelta=inferredDelta, trueA=trueA, inferredA=inferredA, truePhi=truePhi, inferredPhi=inferredPhi, trueC=trueC, inferredC=inferredC))
  
}

```